"""Central schema-version identifiers for persisted and exchanged data."""

SKILL_FILE_SCHEMA_VERSION = "skill_file_v1"
SKILL_MANIFEST_SCHEMA_VERSION = "skill_manifest_v2"
SKILL_PACKAGE_SCHEMA_VERSION = "skill_package_v2"
SKILL_PACKAGE_PATCH_SCHEMA_VERSION = "skill_package_patch_v1"

EXECUTION_PLAN_SCHEMA_VERSION = "execution_plan_v1"
INFERENCE_TRACE_SCHEMA_VERSION = "inference_trace_v2"
GENERATION_AUDIT_SCHEMA_VERSION = "generation_audit_v3"
META_CHECKPOINT_SCHEMA_VERSION = "meta_checkpoint_v2"
ACTIVE_BANK_SCHEMA_VERSION = "active_bank_v3"
PRICING_SCHEMA_VERSION = "pricing_v1"

__all__ = [
    "ACTIVE_BANK_SCHEMA_VERSION",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "GENERATION_AUDIT_SCHEMA_VERSION",
    "INFERENCE_TRACE_SCHEMA_VERSION",
    "META_CHECKPOINT_SCHEMA_VERSION",
    "PRICING_SCHEMA_VERSION",
    "SKILL_FILE_SCHEMA_VERSION",
    "SKILL_MANIFEST_SCHEMA_VERSION",
    "SKILL_PACKAGE_PATCH_SCHEMA_VERSION",
    "SKILL_PACKAGE_SCHEMA_VERSION",
]
